SquirrelPicker in the MultiEditBar is connected
h-be/acorn-ui pull request #102
Opened 2020-01-21 21:10 UTC by Kevjoseph66

![image](https://user-images.githubusercontent.com/57882179/72843462-f43f1500-3c70-11ea-8062-cf69d12543ec.png)

2020-01-21 22:01 UTC, Kevjoseph66 commented
![image](https://user-images.githubusercontent.com/57882179/72847023-1a1be800-3c78-11ea-8d05-d74b6deb450f.png)

2020-01-21 22:22 UTC, Connoropolous commented on src/components/ExpandedViewMode/ExpandedViewMode.js
> +        const squirrels = state.agents[goalMember.agent_address]
```suggestion
        const squirrel = state.agents[goalMember.agent_address]
```

2020-01-21 22:22 UTC, Connoropolous commented on src/components/ExpandedViewMode/ExpandedViewMode.js
> +        const squirrels = state.agents[goalMember.agent_address]
then rename the following two references from `squirrels` to `squirrel` as well

2020-01-21 22:23 UTC, Connoropolous commented on src/components/ExpandedViewMode/ExpandedViewModeContent/ExpandedViewModeContent.js
> +          archiveMemberOfGoal(squirrel.goalMemberAddress)
make it so that when you click, it also closes the little popup

2020-01-21 22:23 UTC, Connoropolous commented on src/components/ExpandedViewMode/ExpandedViewModeHeader/ExpandedViewModeHeader.js
> +          <Icon
Use the `StatusIcon` component here instead

2020-01-21 22:24 UTC, Connoropolous requested changes
Good work, some minor changes requested

2020-01-23 01:50 UTC, Connoropolous approved these changes

2020-01-24 00:34 UTC, merged