css in progress
h-be/acorn-ui pull request #23
Opened 2019-11-14 16:47 UTC by hector0513

![image](https://user-images.githubusercontent.com/16279205/68877740-f028d100-06dc-11ea-9521-810cac7bbcde.png)

2019-11-15 20:46 UTC, alex1812r commented
![image](https://user-images.githubusercontent.com/44066398/68974548-6a358480-07c7-11ea-9b85-af2f02ef5f0d.png)

2019-11-18 15:20 UTC, Connoropolous requested changes
It is great to see you using `function` style React components, thanks for reading up on that. I have a few little styling suggestions relating to the zooming feature.

Great progress.

2019-11-18 15:20 UTC, Connoropolous commented on src/components/Zoom/Options.js
> +      }
These two functions are identical, so they could be brought down to just one function, with a general name `zoom`

2019-11-18 15:20 UTC, Connoropolous commented on src/components/Zoom/ZoomOptions.css
> +  bottom: 0;
```suggestion
  bottom: 10px;
```

2019-11-18 15:20 UTC, Connoropolous commented on src/components/Zoom/ZoomOptions.css
> +  right: 0;
```suggestion
  right: 10px;
```

2019-11-18 15:20 UTC, Connoropolous commented on src/zoom/actions.js
> +}
This file doesn't get used so just delete?

2019-11-18 15:20 UTC, Connoropolous commented on src/zoom/reducer.js
> +const defaultState=null
This file doesn't get used so just delete?

2019-11-18 15:20 UTC, Connoropolous commented on src/components/HierarchyPicker/HierarchyPicker.js
> +        <div className="hierarchy_option" onClick={()=>{ onClick(hierarchy) }}>
`hierarchy` here is an undefined variable, which causes an error, when you click

2019-11-18 15:20 UTC, Connoropolous commented on src/holochainConfig.js
If you change this, don't git commit it, because it breaks other peoples development setups

2019-11-18 15:20 UTC, Connoropolous commented on src/components/VerticalActionsList.js
> +        <Icon name='hierarchy.png' />
I think there is no image with this name, image looks broken

2019-11-18 15:26 UTC, Connoropolous commented on src/components/App.js
> +    <Options/>
```suggestion
    {/* agentAddress is being used as a "loading" variable */}
    {agentAddress && <Options/>}
```

2019-11-18 15:48 UTC, alex1812r commented on src/components/Zoom/ZoomOptions.css
> +  right: 0;
done

2019-11-18 16:21 UTC, Connoropolous commented
fixed up the styling of it a bit
<img width="249" alt="Screen Shot 2019-11-18 at 11 20 52 AM" src="https://user-images.githubusercontent.com/1409121/69070037-7f8ff600-09f5-11ea-83db-49946a8ecf68.png">

2019-11-18 16:50 UTC, Connoropolous approved these changes
approving the zooming changes, and we'll merge. The hierarchy stuff still needs work

2019-11-18 16:50 UTC, merged