only json
h-be/acorn-ui pull request #35
Opened 2019-11-21 16:01 UTC by hector0513

![image](https://user-images.githubusercontent.com/16279205/69354531-a4cf6f00-0c56-11ea-9f51-4af2b1e825d1.png)

2019-11-21 16:01 UTC, hector0513 commented
working progress

2019-11-21 17:54 UTC, Connoropolous commented on src/components/Header/ListExport.js
> +     blob = new Blob([JSON.stringify(data)],{type:""})
```suggestion
     blob = new Blob([JSON.stringify(data, null 2)],{type:""})
```

by doing this, you get JSON with nice formatting :)

2019-11-26 15:25 UTC, Connoropolous commented
@hector0513 we need to separate lists by type in the CSV format. 

agents
____

goals
____

etc. 


<img width="796" alt="Screen Shot 2019-11-26 at 10 23 46 AM" src="https://user-images.githubusercontent.com/1409121/69647084-e2594100-1036-11ea-942c-c1adcdc67eda.png">

2019-11-27 22:01 UTC, hector0513 commented
> @hector0513 we need to separate lists by type in the CSV format.
> 
> agents
> 
> goals
> 
> etc.
> 
> <img alt="Screen Shot 2019-11-26 at 10 23 46 AM" width="796" src="https://user-images.githubusercontent.com/1409121/69647084-e2594100-1036-11ea-942c-c1adcdc67eda.png">


![image](https://user-images.githubusercontent.com/16279205/69762169-ce4d3680-113f-11ea-8581-f484d13347e5.png)
i already fix it

2019-11-27 22:32 UTC, Connoropolous commented
how do we tell the difference between table headers and values? 

I can tell the difference, but Sam, Pegah, or someone else likely couldn't. 

Can we add line breaks between tables?

2019-11-28 13:32 UTC, hector0513 commented
> ¿Cómo distinguimos la diferencia entre los encabezados de tabla y los valores?
> 
> Puedo notar la diferencia, pero Sam, Pegah u otra persona probablemente no podrían.
> 
> ¿Podemos agregar saltos de línea entre tablas?

Like this ?
![image](https://user-images.githubusercontent.com/16279205/69810302-f4b3b600-11c1-11ea-8699-d49e8f4867eb.png)

2019-11-28 14:08 UTC, alex1812r commented
![image](https://user-images.githubusercontent.com/44066398/69812659-f8960700-11c6-11ea-8c41-6b639f4371df.png)

2019-11-28 15:42 UTC, Connoropolous requested changes
So close to complete. Nice work

2019-11-28 15:42 UTC, Connoropolous commented on src/components/ListExport/Popup/Popup.js
> +        <img src="/img/x.svg"/>
Please use the `<Icon />` component that already exists in the project

2019-11-28 15:42 UTC, Connoropolous commented on src/components/ListExport/Popup/Popup.js
> +            <img src="/img/export.svg" />
And here

2019-11-28 15:42 UTC, Connoropolous commented on src/components/Header/Header.js
> +    console.log(bool)
```suggestion
```

2019-11-28 15:42 UTC, Connoropolous commented on src/components/Header/Header.js
> +      listaExport: [{ title: "Export s JSON",type:"json", download:"table.json" },
```suggestion
      listaExport: [{ title: "Export as JSON",type:"json", download:"table.json" },
```

2019-11-28 15:42 UTC, Connoropolous commented on src/components/Header/Header.js
> +    const data ="hola"
?

2019-11-28 15:42 UTC, Connoropolous commented on src/components/ListExport/ListExport.js
> +    if (agents.length > 0) csvRows.push(loop(agents, data.agents));
```suggestion
    if (agents.length > 0) csvRows.push(loop("agents", agents, data.agents));
```

2019-11-28 15:42 UTC, Connoropolous commented on src/components/ListExport/ListExport.js
> +    const loop = (heardes, data) => {
```suggestion
    const loop = (dataset, heardes, data) => {
```

2019-11-28 15:42 UTC, Connoropolous commented on src/components/ListExport/ListExport.js
> +      csvRows.push(Object.keys(data[heardes[0]]).join(","));
```suggestion
      csvRows.push(dataset)
      csvRows.push(Object.keys(data[heardes[0]]).join(","));
```

2019-11-28 15:42 UTC, Connoropolous commented on src/components/ListExport/ListExport.js
> +    if (goals.length > 0) csvRows.push("\n" + loop(goals, data.goals));
```suggestion
    if (goals.length > 0) csvRows.push("\n" + loop("goals", goals, data.goals));
```

2019-11-28 15:42 UTC, Connoropolous commented on src/components/ListExport/ListExport.js
> +    if (edges.length > 0) csvRows.push("\n" + loop(edges, data.edges));
```suggestion
    if (edges.length > 0) csvRows.push("\n" + loop("edges", edges, data.edges));
```

2019-11-28 15:42 UTC, Connoropolous commented on src/components/ListExport/ListExport.js
> +      csvRows.push("\n" + loop(goalMembers, data.goalMembers));
```suggestion
      csvRows.push("\n" + loop("goalMembers", goalMembers, data.goalMembers));
```

2019-11-28 16:00 UTC, Connoropolous commented
This button in the popup doesn't work at the moment. 

<img width="223" alt="Screen Shot 2019-11-28 at 10 57 04 AM" src="https://user-images.githubusercontent.com/1409121/69820050-39dde500-11ce-11ea-973e-98369d9e0bb1.png">

2019-11-28 16:02 UTC, Connoropolous requested changes
only very small changes still left here now

2019-11-28 16:02 UTC, Connoropolous commented on src/components/ListExport/Popup/Popup.js
> +            <label htmlFor="">Dont't show me again</label>
```suggestion
            <label htmlFor="">Don't show me again</label>
```

2019-11-28 16:02 UTC, Connoropolous commented on src/components/ListExport/Popup/Popup.js
> +          <button className="btn-accept">
Use our custom `<Button />` component here instead, and attach an `onClick` listener to it

2019-11-28 16:05 UTC, Connoropolous commented on src/components/ListExport/Popup/Popup.js
> +export default function Popup({ active, handleToHide },props){
```suggestion
export default function Popup({ active, handleToHide }){
```

2019-11-28 16:06 UTC, Connoropolous commented on src/components/ListExport/Popup/Popup.js
> +         <Icon name="/img/x.svg" />
Icon needs to be imported. and remove the `button` wrapper and just attach `onClick` to this `Icon` element

2019-11-28 16:10 UTC, Connoropolous commented on src/components/ListExport/Popup/Popup.js
> +         <Icon name="/img/x.svg" />
`<Icon name="x.svg" onClick={handleToHide} />`

2019-11-28 16:10 UTC, Connoropolous commented on src/components/ListExport/Popup/Popup.js
> +              <Icon name="/img/export.svg"/>
`<Icon name="export.svg" />`

2019-11-28 18:01 UTC, Connoropolous approved these changes
Good job guys!

🎉 🎉 🎉

2019-11-28 18:01 UTC, merged