Expanded view mode
h-be/acorn-ui pull request #47
Opened 2019-12-02 20:08 UTC by hector0513

![image](https://user-images.githubusercontent.com/16279205/69991391-f19c2b00-151d-11ea-9900-24a0cd6b276b.png)

2019-12-03 14:48 UTC, alex1812r commented
![image](https://user-images.githubusercontent.com/44066398/70061244-4ee5ba00-15ba-11ea-9698-1ecf2b3d231f.png)

2019-12-03 16:56 UTC, Connoropolous commented
I will try to look at this asap

2019-12-04 18:35 UTC, Connoropolous requested changes
This is a very small 'request changes'. It looks and works very well

2019-12-04 18:35 UTC, Connoropolous commented on src/components/ExpandedViewMode/ExpandedViewModeContent/ExpandedViewModeContent.js
> +  const handleOnChange = ({ target }) => {
Maybe just create two separate event handlers?

2019-12-04 18:35 UTC, Connoropolous commented on src/holochainConfig.js
> +export const DEFAULT_HOLOCHAIN_HOST = '192.168.1.63'
Revert this back before merging.

2019-12-04 18:46 UTC, hector0513 commented on src/holochainConfig.js
> +export const DEFAULT_HOLOCHAIN_HOST = '192.168.1.63'
done

2019-12-04 18:46 UTC, hector0513 commented on src/components/ExpandedViewMode/ExpandedViewModeContent/ExpandedViewModeContent.js
> +  const handleOnChange = ({ target }) => {
done

2019-12-04 19:02 UTC, Connoropolous commented on src/components/ExpandedViewMode/ExpandedViewModeContent/ExpandedViewModeContent.js
> +  const handleOnChangeTittle = ({ target }) => {
```suggestion
  const handleOnChangeTitle = ({ target }) => {
```

2019-12-04 19:03 UTC, Connoropolous commented on src/components/ExpandedViewMode/ExpandedViewModeContent/ExpandedViewModeContent.js
> +            onKeyPress={handleOnChangeTittle}
```suggestion
            onKeyPress={handleOnChangeTitle}
```

2019-12-04 19:05 UTC, Connoropolous approved these changes
once you merge those tiny spelling fixes, merge it :)

2019-12-04 19:15 UTC, merged